# ??????
server:
  port: 8122
  servlet:
    context-path: /api
spring:
  application:
    name: eoj-backend-user-service
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eoj
    username: root
    password: 123456
# MybatisPlus ??
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete      # ????????????
      logic-delete-value: 1             # ?????????? 1?
      logic-not-delete-value: 0         # ?????????? 0?
# Knife4j ??
knife4j:
  enable: true
  openapi:
    title: "eoj????"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.enndfp.eojbackenduserservice.controller
codesandbox:
  type: remote