# 公共配置文件
server:
  port: 8123
  servlet:
    context-path: /api/file
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
spring:
  application:
    name: eoj-backend-file-service
  # 默认 dev 环境
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eoj
    username: root
    password: 123456
# MybatisPlus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete      # 全局逻辑删除的实体字段名
      logic-delete-value: 1             # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0         # 逻辑未删除值（默认为 0）
# Knife4j 配置
knife4j:
  enable: true
codesandbox:
  type: remote
# 阿里云对象存储
aliyun:
  oss:
    file:
      endpoint: xxx
      accessKeyId: xxx
      accessKeySecret: xxx
      bucketName: xxx